### ISSUE TITLE
running two docker-zerotier on same network ID

### ISSUE THREAD

**Issue by ceo0x** [crocandr/docker-zerotier#1]
Hello , i tried running on my macbook and other instance at my imac, but they getting same peer ID.. so it ends up showing only one at the ZeroTier panel. 

Do you know how to fix this ?

**Comment by crocandr** [comment]
Hi,

Thanks for the issue.

Looks like works by design. :(
I've tried this with two virtual machines on my PC and got same peer ID on both VM. :(

It works if you connect two different LAN networks through one Zerotier node (1 on A site, and 1 on B site), but looks like doesn't work per device (?).
I've used zerotier as a software mesh vpn/router to connect more networks.

Have you tried the "native" client? https://www.zerotier.com/download/
Maybe works a little different...

Another alternative: https://remote.it/

I hope it helps...
